extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
pipelines:
  pullRequest:
    build:
      steps:
      - sh: echo IT IS CUSTOM BUILD PACK
      - sh: npm install
  release:
    build:
      steps:
      - sh: echo IT IS CUSTOM BUILD PACK
      - sh: npm install
  feature:
    build:
      steps:
      - sh: echo IT IS CUSTOM BUILD PACK
      - sh: npm install
